name: Android CI Workflow

on:
  pull_request:
    branches: ["main"]

jobs:
  android-ci:
    name: Android CI Check  # ✅ Add checks에서 이 이름이 뜹니다
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: echo "✅ Hello, this check will succeed."
