name: Android Compose Build Docker

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Android Compose Build Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Force failure to register status check
        run: |
          echo "Forcing failure to register check..."
          exit 1
